[package]
name = "libhaven"
version = "0.1.0"
edition = "2024"

[dependencies]
openmls = "0.7.1"
openmls_basic_credential = "0.4.1"
openmls_rust_crypto = "0.4.1"
openmls_sqlite_storage = "0.1.1"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = "1.0.228"
serde_json = "1.0.145"
